apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: proxy
spec:
  hostname: nginx-in-b
  containers:
    - name: nginx
      image: nginxdemos/hello
      ports:
        - containerPort: 80
          name: http-web-svc

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http-web-svc